# https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/
# alternate: kubectl run -it --rm --restart=Never --image=infoblox/dnstools:latest dnstools
# kubectl apply -f https://k8s.io/examples/admin/dns/dnsutils.yaml
# kubectl exec -i -t dnsutils -- nslookup kubernetes.default
# kubectl get pods --namespace=kube-system -l k8s-app=kube-dns
# kubectl logs --namespace=kube-system -l k8s-app=kube-dns
# kubectl get svc --namespace=kube-system
# kubectl get endpoints kube-dns --namespace=kube-system
# kubectl -n kube-system edit configmap coredns
---
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  # namespace: default
spec:
  containers:
  - name: dnsutils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

