---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  namespace: {{ .Values.argo_ns }}
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
  project: default
  source:
    path: charts/influxdb
    repoURL: https://influxdata.github.io/helm-charts
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
