---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: network-conf-1
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "bridge",
    "bridge": "br-1",
    "isDefaultGateway": true,
    "promiscMode": true,
    "ipam": {
      "type": "host-local",
      "ranges": [
        [
          {
            "subnet": "10.10.0.0/16",
            "rangeStart": "10.10.1.20",
            "rangeEnd": "10.10.3.50"
          }
        ]
      ],
      "routes": [
          { "dst": "0.0.0.0/0" }
      ]   
    }   
  }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: network-conf-1-1
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "bridge",
      "bridge": "br-2",
      "isDefaultGateway": true,
      "promiscMode": true,
      "ipam": {
        "type": "host-local",
        "ranges": [
          [
            {
              "subnet": "55.0.0.0/16",
              "rangeStart": "55.0.0.11",
              "rangeEnd": "55.0.0.21"
            }
          ]
        ],
        "routes": [
            { "dst": "0.0.0.0/0" }
        ]   
      }   
    }'  
