---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: network-conf-1-1
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "bridge",
    "bridge": "south-bridge",
    "promiscMode": true,
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "20.0.0.20/24",
          "gateway": "20.0.0.1"
        }
      ],
      "routes": [
        { "dst": "0.0.0.0/0" }
      ]
    }
  }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: network-conf-2-1
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "bridge",
    "bridge": "north-bridge",
    "promiscMode": true,
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "20.0.0.30/24",
          "gateway": "20.0.0.1"
        }
      ],
      "routes": [
        { "dst": "0.0.0.0/0" }
      ]
    }
  }'
---
apiVersion: v1
kind: Pod
metadata:
  name: srv-pod-1
  annotations:
    k8s.v1.cni.cncf.io/networks: network-conf-1@north0
spec:
  containers:
  - name: srv-pod-1
    securityContext:
      privileged: true
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
