apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodered.fullname" . }}
  labels:
    {{- include "nodered.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nodered.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nodered.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nodered.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          # env:
          #   - name: NODE_RED_CREDENTIAL_SECRET
          #     value: contrail123
          ports:
            - name: http
              containerPort: 1880
              protocol: TCP

          volumeMounts:
            - mountPath: /data
              name: nodered-data
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: nodered-data
          persistentVolumeClaim:
            claimName: nodered-data-pvc
          
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodered-data-pv
  labels:
    directory: tftpboot
spec:
  storageClassName: local-path 
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /var/nodered
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: k3s.io/hostname
              operator: In
              values:
                - k3s
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodered-data-pvc
spec:
  storageClassName: local-path
  volumeName: nodered-data-pv
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
