apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodered.fullname" . }}
  labels:
    {{- include "nodered.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.externalTrafficPolicy }}
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nodered.selectorLabels" . | nindent 4 }}
